spring:
  http:
    encoding:
      force: true
      charset: UTF-8
  #freemarker
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: classpath:/pages
  #mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/analysisFile?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root123
  #jpa
  jpa:
    show-sql: true